# -*- coding: utf-8 -*-
"""elecciones.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CYR0UhlYnedS4tV9D4m8luZGaP_BH5ld
"""

def candidatos(lista):
  a=[]
  for i in lista:
    if i not in a:
      a.append(i)
  return a

def auditoria1(lis_pos, lis_vot, nom_can):
  z=[i for i,val in enumerate(lis_vot) if val==nom_can]
  b=[]
  for i in lis_pos:
    if i in z:
      b.append(i)
  return b

def auditoria2(x,y):
  c=[]
  for i in x:
    if i not in y:
      c.append(i)   
  return c

def diferencia(k,l):
  d=[]
  e=[]
  for i in k:
    if i not in l:
      d.append(i)
  
  for i in l:
    if i not in k:
      e.append(i)

  return min(len(d), len(e))